name: Embla
description: Voice-driven Icelandic-language digital assistant.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.12.1'
  sound_stream: '>=0.2.0'
  audioplayers: '>=0.16.2'
  shared_preferences: '>=0.5.7'
  geolocator: '>=6.1.4'
  webview_flutter: '>=1.0.3'
  package_info: '>=0.4.3'
  device_id: '>=0.0.1'
  url_launcher: '>=5.7.8'
  google_speech: '>=1.2.1'
  connectivity: '>=2.0.1'
  flutter_inappwebview: '>=4.0.0+4'
  rxdart: '>=0.20.0'
  dart_numerics: '>=0.0.5'
  wakelock: '>=0.2.1+1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: '>=1.15.4'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Images
    - assets/images/cube.png
    - assets/images/mic.png
    - assets/images/mic-slash.png
    - assets/images/menu.png
    - assets/images/cog.png
    # - assets/images/logo.png
    # Audio
    - assets/audio/rec_begin.wav
    - assets/audio/rec_cancel.wav
    - assets/audio/rec_confirm.wav
    - assets/audio/conn-dora.wav
    - assets/audio/conn-karl.wav
    - assets/audio/dunno-dora.wav
    - assets/audio/dunno-karl.wav
    - assets/audio/err-dora.wav
    - assets/audio/err-karl.wav
    # Docs
    - docs/about.html
    - docs/instructions.html
    - docs/privacy.html
    - docs/style.css
    - docs/Lato-Regular.woff2
    - docs/Lato-Italic.woff2
    - docs/Lato-Bold.woff2
    # Keys
    - assets/keys/gaccount.json
    - assets/keys/GreynirAPI.key
    # Logo animation frames
    - assets/images/anim/logo/anim_00000.png
    - assets/images/anim/logo/anim_00001.png
    - assets/images/anim/logo/anim_00002.png
    - assets/images/anim/logo/anim_00003.png
    - assets/images/anim/logo/anim_00004.png
    - assets/images/anim/logo/anim_00005.png
    - assets/images/anim/logo/anim_00006.png
    - assets/images/anim/logo/anim_00007.png
    - assets/images/anim/logo/anim_00008.png
    - assets/images/anim/logo/anim_00009.png
    - assets/images/anim/logo/anim_00010.png
    - assets/images/anim/logo/anim_00011.png
    - assets/images/anim/logo/anim_00012.png
    - assets/images/anim/logo/anim_00013.png
    - assets/images/anim/logo/anim_00014.png
    - assets/images/anim/logo/anim_00015.png
    - assets/images/anim/logo/anim_00016.png
    - assets/images/anim/logo/anim_00017.png
    - assets/images/anim/logo/anim_00018.png
    - assets/images/anim/logo/anim_00019.png
    - assets/images/anim/logo/anim_00020.png
    - assets/images/anim/logo/anim_00021.png
    - assets/images/anim/logo/anim_00022.png
    - assets/images/anim/logo/anim_00023.png
    - assets/images/anim/logo/anim_00024.png
    - assets/images/anim/logo/anim_00025.png
    - assets/images/anim/logo/anim_00026.png
    - assets/images/anim/logo/anim_00027.png
    - assets/images/anim/logo/anim_00028.png
    - assets/images/anim/logo/anim_00029.png
    - assets/images/anim/logo/anim_00030.png
    - assets/images/anim/logo/anim_00031.png
    - assets/images/anim/logo/anim_00032.png
    - assets/images/anim/logo/anim_00033.png
    - assets/images/anim/logo/anim_00034.png
    - assets/images/anim/logo/anim_00035.png
    - assets/images/anim/logo/anim_00036.png
    - assets/images/anim/logo/anim_00037.png
    - assets/images/anim/logo/anim_00038.png
    - assets/images/anim/logo/anim_00039.png
    - assets/images/anim/logo/anim_00040.png
    - assets/images/anim/logo/anim_00041.png
    - assets/images/anim/logo/anim_00042.png
    - assets/images/anim/logo/anim_00043.png
    - assets/images/anim/logo/anim_00044.png
    - assets/images/anim/logo/anim_00045.png
    - assets/images/anim/logo/anim_00046.png
    - assets/images/anim/logo/anim_00047.png
    - assets/images/anim/logo/anim_00048.png
    - assets/images/anim/logo/anim_00049.png
    - assets/images/anim/logo/anim_00050.png
    - assets/images/anim/logo/anim_00051.png
    - assets/images/anim/logo/anim_00052.png
    - assets/images/anim/logo/anim_00053.png
    - assets/images/anim/logo/anim_00054.png
    - assets/images/anim/logo/anim_00055.png
    - assets/images/anim/logo/anim_00056.png
    - assets/images/anim/logo/anim_00057.png
    - assets/images/anim/logo/anim_00058.png
    - assets/images/anim/logo/anim_00059.png
    - assets/images/anim/logo/anim_00060.png
    - assets/images/anim/logo/anim_00061.png
    - assets/images/anim/logo/anim_00062.png
    - assets/images/anim/logo/anim_00063.png
    - assets/images/anim/logo/anim_00064.png
    - assets/images/anim/logo/anim_00065.png
    - assets/images/anim/logo/anim_00066.png
    - assets/images/anim/logo/anim_00067.png
    - assets/images/anim/logo/anim_00068.png
    - assets/images/anim/logo/anim_00069.png
    - assets/images/anim/logo/anim_00070.png
    - assets/images/anim/logo/anim_00071.png
    - assets/images/anim/logo/anim_00072.png
    - assets/images/anim/logo/anim_00073.png
    - assets/images/anim/logo/anim_00074.png
    - assets/images/anim/logo/anim_00075.png
    - assets/images/anim/logo/anim_00076.png
    - assets/images/anim/logo/anim_00077.png
    - assets/images/anim/logo/anim_00078.png
    - assets/images/anim/logo/anim_00079.png
    - assets/images/anim/logo/anim_00080.png
    - assets/images/anim/logo/anim_00081.png
    - assets/images/anim/logo/anim_00082.png
    - assets/images/anim/logo/anim_00083.png
    - assets/images/anim/logo/anim_00084.png
    - assets/images/anim/logo/anim_00085.png
    - assets/images/anim/logo/anim_00086.png
    - assets/images/anim/logo/anim_00087.png
    - assets/images/anim/logo/anim_00088.png
    - assets/images/anim/logo/anim_00089.png
    - assets/images/anim/logo/anim_00090.png
    - assets/images/anim/logo/anim_00091.png
    - assets/images/anim/logo/anim_00092.png
    - assets/images/anim/logo/anim_00093.png
    - assets/images/anim/logo/anim_00094.png
    - assets/images/anim/logo/anim_00095.png
    - assets/images/anim/logo/anim_00096.png
    - assets/images/anim/logo/anim_00097.png
    - assets/images/anim/logo/anim_00098.png
    - assets/images/anim/logo/anim_00099.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
