name: Embla
description: Voice-driven Icelandic-language digital assistant.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  sound_stream: ^0.2.0
  audioplayers: ^0.16.2
  shared_preferences: ^0.5.7
  geolocator: ^6.1.4
  webview_flutter: ^1.0.3
  package_info: ^0.4.3
  device_id: '>=0.0.1'
  url_launcher: ^5.7.8
  google_speech: '>=1.2.1'
  connectivity: ^2.0.1
  flutter_inappwebview: ^4.0.0+4

  # flutter_sphinx:
  #   git:
  #     url: https://github.com/dustin-graham/flutter_sphinx
  #     ref: master

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: '>=1.15.4'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Images
    - assets/images/cube.png
    - assets/images/mic.png
    - assets/images/mic-slash.png
    - assets/images/menu.png
    - assets/images/logo.png
    - assets/images/animation.apng
    # Audio
    - assets/audio/rec_begin.wav
    - assets/audio/rec_cancel.wav
    - assets/audio/rec_confirm.wav
    - assets/audio/conn-dora.wav
    - assets/audio/conn-karl.wav
    - assets/audio/dunno-dora.wav
    - assets/audio/dunno-karl.wav
    - assets/audio/err-dora.wav
    - assets/audio/err-karl.wav
    # Docs
    - docs/about.html
    - docs/instructions.html
    - docs/privacy.html
    - docs/style.css
    - docs/Lato-Regular.woff2
    - docs/Lato-Italic.woff2
    - docs/Lato-Bold.woff2
    # Other
    - assets/test_service_account.json
    # Logo animation frames
    - assets/anim/logo/EMBLA_256px_00000.png
    - assets/anim/logo/EMBLA_256px_00001.png
    - assets/anim/logo/EMBLA_256px_00002.png
    - assets/anim/logo/EMBLA_256px_00003.png
    - assets/anim/logo/EMBLA_256px_00004.png
    - assets/anim/logo/EMBLA_256px_00005.png
    - assets/anim/logo/EMBLA_256px_00006.png
    - assets/anim/logo/EMBLA_256px_00007.png
    - assets/anim/logo/EMBLA_256px_00008.png
    - assets/anim/logo/EMBLA_256px_00009.png
    - assets/anim/logo/EMBLA_256px_00010.png
    - assets/anim/logo/EMBLA_256px_00011.png
    - assets/anim/logo/EMBLA_256px_00012.png
    - assets/anim/logo/EMBLA_256px_00013.png
    - assets/anim/logo/EMBLA_256px_00014.png
    - assets/anim/logo/EMBLA_256px_00015.png
    - assets/anim/logo/EMBLA_256px_00016.png
    - assets/anim/logo/EMBLA_256px_00017.png
    - assets/anim/logo/EMBLA_256px_00018.png
    - assets/anim/logo/EMBLA_256px_00019.png
    - assets/anim/logo/EMBLA_256px_00020.png
    - assets/anim/logo/EMBLA_256px_00021.png
    - assets/anim/logo/EMBLA_256px_00022.png
    - assets/anim/logo/EMBLA_256px_00023.png
    - assets/anim/logo/EMBLA_256px_00024.png
    - assets/anim/logo/EMBLA_256px_00025.png
    - assets/anim/logo/EMBLA_256px_00026.png
    - assets/anim/logo/EMBLA_256px_00027.png
    - assets/anim/logo/EMBLA_256px_00028.png
    - assets/anim/logo/EMBLA_256px_00029.png
    - assets/anim/logo/EMBLA_256px_00030.png
    - assets/anim/logo/EMBLA_256px_00031.png
    - assets/anim/logo/EMBLA_256px_00032.png
    - assets/anim/logo/EMBLA_256px_00033.png
    - assets/anim/logo/EMBLA_256px_00034.png
    - assets/anim/logo/EMBLA_256px_00035.png
    - assets/anim/logo/EMBLA_256px_00036.png
    - assets/anim/logo/EMBLA_256px_00037.png
    - assets/anim/logo/EMBLA_256px_00038.png
    - assets/anim/logo/EMBLA_256px_00039.png
    - assets/anim/logo/EMBLA_256px_00040.png
    - assets/anim/logo/EMBLA_256px_00041.png
    - assets/anim/logo/EMBLA_256px_00042.png
    - assets/anim/logo/EMBLA_256px_00043.png
    - assets/anim/logo/EMBLA_256px_00044.png
    - assets/anim/logo/EMBLA_256px_00045.png
    - assets/anim/logo/EMBLA_256px_00046.png
    - assets/anim/logo/EMBLA_256px_00047.png
    - assets/anim/logo/EMBLA_256px_00048.png
    - assets/anim/logo/EMBLA_256px_00049.png
    - assets/anim/logo/EMBLA_256px_00050.png
    - assets/anim/logo/EMBLA_256px_00051.png
    - assets/anim/logo/EMBLA_256px_00052.png
    - assets/anim/logo/EMBLA_256px_00053.png
    - assets/anim/logo/EMBLA_256px_00054.png
    - assets/anim/logo/EMBLA_256px_00055.png
    - assets/anim/logo/EMBLA_256px_00056.png
    - assets/anim/logo/EMBLA_256px_00057.png
    - assets/anim/logo/EMBLA_256px_00058.png
    - assets/anim/logo/EMBLA_256px_00059.png
    - assets/anim/logo/EMBLA_256px_00060.png
    - assets/anim/logo/EMBLA_256px_00061.png
    - assets/anim/logo/EMBLA_256px_00062.png
    - assets/anim/logo/EMBLA_256px_00063.png
    - assets/anim/logo/EMBLA_256px_00064.png
    - assets/anim/logo/EMBLA_256px_00065.png
    - assets/anim/logo/EMBLA_256px_00066.png
    - assets/anim/logo/EMBLA_256px_00067.png
    - assets/anim/logo/EMBLA_256px_00068.png
    - assets/anim/logo/EMBLA_256px_00069.png
    - assets/anim/logo/EMBLA_256px_00070.png
    - assets/anim/logo/EMBLA_256px_00071.png
    - assets/anim/logo/EMBLA_256px_00072.png
    - assets/anim/logo/EMBLA_256px_00073.png
    - assets/anim/logo/EMBLA_256px_00074.png
    - assets/anim/logo/EMBLA_256px_00075.png
    - assets/anim/logo/EMBLA_256px_00076.png
    - assets/anim/logo/EMBLA_256px_00077.png
    - assets/anim/logo/EMBLA_256px_00078.png
    - assets/anim/logo/EMBLA_256px_00079.png
    - assets/anim/logo/EMBLA_256px_00080.png
    - assets/anim/logo/EMBLA_256px_00081.png
    - assets/anim/logo/EMBLA_256px_00082.png
    - assets/anim/logo/EMBLA_256px_00083.png
    - assets/anim/logo/EMBLA_256px_00084.png
    - assets/anim/logo/EMBLA_256px_00085.png
    - assets/anim/logo/EMBLA_256px_00086.png
    - assets/anim/logo/EMBLA_256px_00087.png
    - assets/anim/logo/EMBLA_256px_00088.png
    - assets/anim/logo/EMBLA_256px_00089.png
    - assets/anim/logo/EMBLA_256px_00090.png
    - assets/anim/logo/EMBLA_256px_00091.png
    - assets/anim/logo/EMBLA_256px_00092.png
    - assets/anim/logo/EMBLA_256px_00093.png
    - assets/anim/logo/EMBLA_256px_00094.png
    - assets/anim/logo/EMBLA_256px_00095.png
    - assets/anim/logo/EMBLA_256px_00096.png
    - assets/anim/logo/EMBLA_256px_00097.png
    - assets/anim/logo/EMBLA_256px_00098.png
    - assets/anim/logo/EMBLA_256px_00099.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
