name: embla
description: Cross-platform mobile Icelandic-language voice assistant.
publish_to: 'none'
version: 1.4.0+595
homepage: https://embla.is
repository: https://github.com/mideind/EmblaFlutterApp

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # Third-party
  http: '>=1.0.0'
  shared_preferences: '^2.2.2'
  geolocator: '^11.0.0'
  package_info_plus: '4.0.2'
  device_info_plus: '^9.1.2'
  url_launcher: '^6.1.14'
  platform_device_id:
    git:
      url: https://github.com/tommysolsen/platform_device_id.git
      path: platform_device_id
  connectivity_plus: ^5.0.2
  flutter_inappwebview: '^5.7.2+3'
  path_provider: '^2.1.2'
  wakelock_plus: '1.1.1'
  permission_handler: '^10.2.0'
  flutter_fgbg: '^0.3.0'
  logger: '^2.0.1'
  adaptive_theme: '^3.6.0'
  open_settings: '^2.0.2'
  adaptive_dialog: '^1.9.0+2'
  # fluttertoast: '^8.1.2'
  # flutter_spinkit: ^5.1.0
  # multicast_dns: '^0.3.2'
  flutter_animate: '^4.5.0'
  # Ours
  flutter_snowboy: #'>=0.1.2'
    path: '../flutter_snowboy'
    # git:
    #   url: git://github.com/mideind/flutter_snowboy.git
    #   ref: master
  embla_core: #'>=1.0.8'
    path: '../embla_core'
    # git:
    #   url: git://github.com/mideind/EmblaCoreFlutter.git
    #   ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: '>=1.15.4'
  flutter_lints: '>=2.0.1'

# The following section is specific to Flutter.
flutter:
  # Ensures that the Material Icons font is included
  uses-material-design: true
  # The following files will be included in Flutter's asset bundle
  assets:
    # Images
    - assets/images/
    # Audio
    - assets/audio/
    # HTML documentation
    - docs/
    # Hotword models
    - assets/hotword/
    # Logo animation frames
    - assets/images/anim/logo/light/
    # - assets/images/anim/logo/dark/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
