name: embla
description: Icelandic-language voice assistant.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.13.3'
  # intl: '>=0.17.0'
  shared_preferences: '>=2.0.8'
  geolocator: '>=7.7.1'
  package_info_plus: '>=1.3.0'
  platform_device_id: '>=1.0.1'
  url_launcher: '>=6.0.12'
  google_speech: '>=2.0.1'
  connectivity_plus: '>=2.0.2'
  flutter_inappwebview: '>=5.3.2'
  path_provider: '>=2.0.6'
  rxdart: '>=0.27.2'
  # dart_numerics: '>=0.0.5'
  wakelock: '>=0.5.6'
  flutter_sound_lite: '>=8.4.2'
  permission_handler: '>=8.2.5'
  # app_settings: '>=4.1.0'
  flutter_fgbg: '>=0.1.0'
  flutter_webview_plugin: '>=0.4.0'
  logger: '>=1.1.0'
  filesize: '>=2.0.1'
  flutter_snowboy:
    path: ../flutter_snowboy/

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: '>=1.15.4'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # Ensures that the Material Icons font is included
  uses-material-design: true
  # The following files will be included in Flutter's asset bundle
  assets:
    # Images
    - assets/images/
    # Audio
    - assets/audio/
    # HTML documentation
    - docs/
    # Hotword models
    - assets/hotword/
    # Logo animation frames
    - assets/images/anim/logo/bright/
    - assets/images/anim/logo/dark/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
