name: embla
description: Voice-driven Icelandic-language digital assistant.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.12.1'
  intl: '>=0.17.0'
  shared_preferences: '>=0.5.7'
  geolocator: '>=6.1.4'
  package_info: '>=0.4.3'
  device_id: '>=0.0.1'
  url_launcher: '>=5.7.8'
  google_speech: '>=2.0.0'
  connectivity_plus: '>=0.7.1'
  flutter_inappwebview: '>=4.0.0+4'
  path_provider: '>=2.0.0'
  rxdart: '>=0.20.0'
  dart_numerics: '>=0.0.5'
  wakelock: '>=0.5.2'
  flutter_sound_lite: '>=8.0.0-0'
  permission_handler: '>=5.0.1+1'
  # app_settings: '>=4.1.0'
  flutter_fgbg: '>=0.0.1'
  flutter_snowboy:
    path: ../flutter_snowboy/

  # webview_flutter: '>=1.0.7' # Used by incomplete jsexec code

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: '>=1.15.4'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # Ensures that the Material Icons font is included
  uses-material-design: true
  # The following files will be included in Flutter's asset bundle
  assets:
    # Images
    - assets/images/
    # Audio
    - assets/audio/
    # Docs
    - docs/
    # Hotword models
    - assets/hwmodels/
    # Logo animation frames
    - assets/images/anim/logo/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
