name: embla
description: Cross-platform mobile Icelandic-language voice assistant.
publish_to: 'none'
version: 1.3.4+17

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.13.4'
  shared_preferences: '^2.0.15'
  geolocator: '^9.0.2'
  package_info_plus: '^1.4.2'
  platform_device_id: '^1.0.1'
  url_launcher: '^6.1.2'
  google_speech: '^2.1.1'
  connectivity_plus: '^2.3.0'
  flutter_inappwebview: '^5.7.1'
  path_provider: '^2.0.10'
  rxdart: '^0.27.3'
  wakelock: '^0.6.1'
  audio_session: '^0.1.10'
  permission_handler: '^10.2.0'
  flutter_fgbg: '^0.2.0'
  logger: '^1.1.0'
  filesize: '^2.0.1'
  adaptive_theme: '^3.0.0'
  open_settings: '^2.0.2'
  flutter_snowboy: '>=0.1.1'
  flutter_sound: '>9.0.0'
  fluttertoast: '^8.1.2'
  flutter_spinkit: ^5.1.0
  multicast_dns: '^0.3.2'
  flutter_animate: '^3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: '>=1.15.4'
  flutter_lints: '>=2.0.1'

# The following section is specific to Flutter.
flutter:
  # Ensures that the Material Icons font is included
  uses-material-design: true
  # The following files will be included in Flutter's asset bundle
  assets:
    # Images
    - assets/images/
    # Audio
    - assets/audio/
    # HTML documentation
    - docs/
    # Hotword models
    - assets/hotword/
    # Logo animation frames
    - assets/images/anim/logo/light/
    # - assets/images/anim/logo/dark/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
