#import "AppDelegate.h"
#import "GeneratedPluginRegistrant.h"
// Generated by the Swift compiler from EmblaActions.swift. If Xcode cannot
// find this header, check that SWIFT_VERSION and SWIFT_OBJC_BRIDGING_HEADER
// are set on the Runner target.
#import "Runner-Swift.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [GeneratedPluginRegistrant registerWithRegistry:self];
  // Device actions that have no Flutter plugin: reminders, timers, alarms.
  [EmblaActions registerWithRegistrar:[self registrarForPlugin:@"EmblaActions"]];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

@end
