# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
            java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: touch keys/gaccount.json
      - run: touch keys/query_api.key
      - run: bash keys/gen_keys.sh
      - run: git clone https://github.com/mideind/flutter_snowboy ../flutter_snowboy
      - run: flutter pub get
      - run: flutter test
      - run: dart analyze lib
      - run: bash build.sh
      - name: Slack notification
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Integration Testing
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() # Pick up event if the job fails
